project/apps/cliente/urls.py
from django.urls import path
from .views import home, register, login_request, registrar_cliente, CiudadCreate
from django.contrib.auth.views import LogoutView
app_name = "cliente"

urlpatterns = [
    path("", home, name="home"),
    path('register/', register, name="register"),
    path('crear/cliente/', registrar_cliente, name="crear_cliente"),
    path('login/', login_request , name="login"),
    path('logout/', LogoutView.as_view(template_name="cliente/logout.html"), name="logout"),
    path('registrar/ciudad', CiudadCreate.as_view(), name="registrar_ciudad"),
]

project/apps/home/urls.py
from django.urls import path
from .views import home, contacto, contact_view
from cliente.views import login_request
from django.contrib.auth.views import LogoutView

app_name = "home"

urlpatterns = [
    path("", home, name="home"),
    path("contacto/", contact_view, name="contacto"),
    
    
]

project/apps/producto/urls.py
from django.urls import path
from .views import ProductoCreate, CategoriaCreate, ProductoList, ProductoDelete, ProductoUpdate, ProductoDetail

app_name = "producto"

urlpatterns = [
    path("producto/list/", ProductoList.as_view(), name="producto_list"),
    path("producto/create/", ProductoCreate.as_view(), name="producto_create"),
    path("producto/categoriacreate/", CategoriaCreate.as_view(), name="categoria_create"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view(), name="producto_delete"),
    path("producto/update/<int:pk>", ProductoUpdate.as_view(), name="producto_update"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
]

project/apps/venta/urls.py
from django.urls import path
from . import views

app_name = "venta"

urlpatterns = [
    path("", views.home, name="home"),
    path("registrar/pedido/", views.registrar_pedido, name="registrar_pedido"),
    path("venta/list/", views.VentaList.as_view(), name="venta_list"),
    path("registrar/tiposervicio/", views.TipoServicioCreateView.as_view(), name="registrar_tiposervicio"),
    path("servicios", views.servicios, name="servicios"),
    path("registrar/servicio/", views.ServicioCreateView.as_view(), name="registrar_servicio"),
    path("confirmar", views.confirmar, name="confirmar"),
    path('servicio/list/', views.ServicioList.as_view(), name="servicio_list"),
    path("servicio/detail/<int:pk>", views.ServicioDetail.as_view(), name="servicio_detail"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/home/models.py
from django.db import models

# Create your models here.

project/apps/home/forms.py
from django import forms

class ContactForm(forms.Form):
    nombre = forms.CharField(label='nombre', max_length=100)
    email = forms.EmailField(label='email', max_length=100)
    mensaje = forms.CharField(label='mensaje', widget=forms.Textarea)

project/apps/home/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from .forms import ContactForm
from django.http import HttpRequest, HttpResponse

# Create your views here.
def home(request):
    return render(request, "home/base.html")

def contacto(request):
    return render(request, "home/contacto.html")



def contact_view(request: HttpRequest) -> HttpResponse:
    # Desde esta función un usuario no registrado puede enviar un mensaje de contacto para consultas
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            email = form.cleaned_data['email']
            mensaje = form.cleaned_data['mensaje']

        
            subject = f"Mensaje de contacto de {nombre}"
            body = f"Email del remitente: {email}\n\nMensaje:\n{mensaje}"
            sender_email = 'caro_negrin@hotmail.com' 

        
            send_mail(subject, body, sender_email, ['caro_negrin@hotmail.com'])  
            mensaje_enviado= f"{nombre}, su mensaje ha sido enviado correctamente. Nos pondemos en contaco a la brevedad. Muchas Gracias!"
          
            return render(request, 'home/index.html', {'mensaje': mensaje_enviado})

    else:
        form = ContactForm()

    return render(request, 'home/contacto.html', {'form': form})

project/apps/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}    
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Super Regalería</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" {% static 'home/assets/icono.png' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body id="page-top">
        <!-- Navigation-->
        {% include 'home/navbar.html' %}
       
        
        
        {% block CONTENIDO_BASE %}
            <!-- Masthead-->
            <header class="masthead">
                <div class="container">
                    <div class="masthead-subheading">Encontrá el regalo IDEAL</div>
                    <div class="masthead-heading text-uppercase">Bienvenido a La Super Regalería</div>
                    {% if user.is_staff %}
                            <a href="{% url 'admin:index' %}" class="btn btn-primary ">Panel de Administración</a>
                        
                    {% else %}
                        <a class="btn btn-primary btn-xl text-uppercase" href="https://wa.me/+5492964544342">Enviar Whatsapp</a>
                    {% endif %}

                   
                </div>
            </header>
        {% endblock CONTENIDO_BASE %}

        </section>
        <!-- Footer-->
        {% include 'home/footer.html' %}
     
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

        <script src={% static 'Home/js/scripts.js' %}></script>
    </body>
</html>

project/apps/home/templates/home/contacto.html
{% extends 'home/base.html' %}


{% block CONTENIDO_BASE %}
    

    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h1 class="section-heading">Sobre Nosotros</h1>
                <p class="section-text text-light  text-lg-start ">Somos un emprendimiento familiar, iniciado en el año 2017.
                    Nos dedicamos a la regalería personalizada, y también a productos de reventa, todo relacionado a que puedas encontrar el regalo
                    ideal para cada ocasión. Nos sentimos orgullosos de poder traer a nuestros clientes productos de diseño profesional.
                </p>
                <p class="section-text text-light  text-lg-start ">   
                    Otro de nuestros productos destacados son los vinilos decorativos para paredes y vidrieras, 
                    los cuales hacemos con el diseño que nuestro cliente necesite,
                    Este producto es ideal para aquellos que quieran decorar las paredes de sus casas 
                    o también para aquellos que tengan un negocio
                    y deseen darle un estilo diferente y personalizado.
                </p>

            <h3 class="text-secondary text-light ">Déjanos tu mensaje</h3>
            </div>
            
            <form method="post">
                {% csrf_token %}
                <div class="form-group text-center ">
                    <div>
                        <label for="{{ form.nombre.id_for_label }}" class="label text-light ">Nombre: </label>
                        <div class="column-gap-0 ">{{ form.nombre }}</div>
                    </div>
                    <div>
                        <label for="{{ form.email.id_for_label }}" class="label text-light ">Email:</label>
                        <div class="column-gap-0 ">{{ form.email }}</div>
                    </div>
                    <div>
                        <label for="{{ form.mensaje.id_for_label }}" class="label text-light ">Mensaje:</label>
                        <div class="column-gap-0 ">{{ form.mensaje }}</div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary submit">Enviar Mensaje</button>
                </div>
            </form>

{% endblock CONTENIDO_BASE %}

project/apps/home/templates/home/footer.html
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">Copyright &copy; Super Regalería</div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/profile.php?id=100063119075589" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark btn-social mx-2" href="https://www.instagram.com/nodo.syv/" aria-label="Instagram">ig</a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!">Politicas de Privacidad</a>
                <a class="link-dark text-decoration-none" href="#!">Terminos de Uso</a>
            </div>
        </div>
    </div>
</footer>

project/apps/home/templates/home/index.html
{% extends 'home/base.html' %}
    
{% block CONTENIDO_BASE %}
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">
            {% block TITULO_INDEX %}
        
            {% endblock TITULO_INDEX %}
            
        </div>
        {% block CONTENIDO_INDEX %}
        {{ mensaje }}
        

        {% endblock CONTENIDO_INDEX %}
    </div>
</header>

   

    

{% endblock CONTENIDO_BASE %}

project/apps/home/templates/home/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">Inicio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse bg-black " id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0" >
                {% if user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'cliente:home' %}">Clientes Registrados</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'venta:home' %}">Realizar Pedidos</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'producto:producto_list' %}">Productos</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'venta:servicios' %}">Servicios</a></li>
                    <li class="nav-item"><a class="nav-link text-info" href="{% url 'cliente:logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'cliente:register' %}">Registrarse</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'cliente:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:contacto' %}">Sobre Nosotros</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>