project/apps/producto/urls.py
from django.urls import path
from .views import ProductoCreate, CategoriaCreate, ProductoList, ProductoDelete, ProductoUpdate, ProductoDetail

app_name = "producto"

urlpatterns = [
    path("producto/list/", ProductoList.as_view(), name="producto_list"),
    path("producto/create/", ProductoCreate.as_view(), name="producto_create"),
    path("producto/categoriacreate/", CategoriaCreate.as_view(), name="categoria_create"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view(), name="producto_delete"),
    path("producto/update/<int:pk>", ProductoUpdate.as_view(), name="producto_update"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/producto/models.py
from django.db import models

# Create your models here.

class Categoria (models.Model):
    nombre = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nombre

class Producto (models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)
    categoria_id= models.ForeignKey(Categoria, null=False, blank=False, on_delete=models.CASCADE)
    descripcion = models.TextField(max_length=100, blank=True, null=True)
    precio = models.FloatField(blank=False, null=False)
    stock = models.IntegerField(blank=True, null=True)
    personalizable = models.BooleanField(blank=True, null=True)
    imagen = models.ImageField(upload_to='img_productos', blank=True, null=True)

    def __str__(self):
        return self.nombre

project/apps/producto/forms.py
from django import forms

from . import models


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = models.Categoria
        fields = "__all__"


class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"

project/apps/producto/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from . import forms, models
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

# Create your views here.

class ProductoCreate(CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")

class CategoriaCreate(CreateView):
    model = models.Categoria
    form_class = forms.CategoriaForm
    success_url = reverse_lazy("producto:producto_create")

class ProductoList(ListView):
    model = models.Producto

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Producto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Producto.objects.all()
        return object_list

class ProductoDetail(DetailView):
    model = models.Producto


class ProductoDelete(DeleteView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")


class ProductoUpdate(UpdateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")

project/apps/producto/templates/producto/categoria_form.html
{% extends 'home/index.html' %}

    {% block TITULO_INDEX %} 
        Crear Categoría de productos
    {% endblock TITULO_INDEX %}

    {% block CONTENIDO_INDEX %}
        <div class="row align-items-stretch mb-5">
            <div class="col-md-6">
                <div class="form-group">
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <label for="{{ form.nombre.id_for_label }}" class="form-control bg-primary">Nombre: </label>
                            <div class="form-control-color">{{ form.nombre }}</div>
                        </div>
                        <button type="submit">Guardar</button>
                    </form> 
                </div>
            </div>
        </div>
    {% endblock CONTENIDO_INDEX %}

project/apps/producto/templates/producto/producto_confirm_delete.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %} 
    Eliminación de Productos
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}

    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

{% endblock CONTENIDO_INDEX %}

project/apps/producto/templates/producto/producto_detail.html
{% extends 'home/index.html' %}
{% load static %}

{% block TITULO_INDEX %}
    <h1>{{ object }}</h1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <ul>
        <li>Nombre: {{ object.nombre }} </li>
        <li>Categoría: {{ object.categoria_id.nombre }}</li>
        <li>Descripción: {{ object.descripcion }} </li>
        {% if user.is_staff %}
            <li>Stock: {{ object.stock }}</li>
        {% endif %}
        {% if object.personalizable == True %}
            <li>Personalizable: SI</li>
        {% else %}
            <li>Personalizable: NO</li>
        {% endif %}
       
        <li>Precio: ${{ object.precio }}</li>
        {% if object.imagen.url %}
            <li><img src="{{ object.imagen.url }}" alt="imagen" width="200" ></li>
        {% endif %}
        
    </ul>

{% endblock CONTENIDO_INDEX %}

project/apps/producto/templates/producto/producto_form.html
{% extends 'home/index.html' %}

    {% block TITULO_INDEX %} 
        Crear/Actualizar Productos
    {% endblock TITULO_INDEX %}

    {% block CONTENIDO_INDEX %}
        <div class="row align-items-stretch mb-5">
            <div class="col-md-6">
                <div class="form-group">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label for="{{ form.nombre.id_for_label }}" class="form-control bg-primary">Nombre: </label>
                            <div class="form-control-color">{{ form.nombre }}</div>
                        </div>
                        <div>
                            <label for="{{ form.categoria_id.id_for_label }}" class="form-control bg-primary ">Categoría: </label>
                            <div class="form-control-color">{{ form.categoria_id }} </div> <div> <a href="{% url 'producto:categoria_create' %}" class="btn btn-secondary  btn-sn">Agregar categoría</a></div>
                        </div>
                        <div>
                            <label for="{{ form.descripcion.id_for_label }}" class="form-control bg-primary ">Descripción: </label>
                            <div class="text-start ">{{ form.descripcion }}</div>
                        </div>
                        <div>
                            <label for="{{ form.precio.id_for_label }}" class="form-control bg-primary ">Precio: </label>
                            <div class="form-control-color">{{ form.precio }}</div>
                        </div>
                        <div>
                            <label for="{{ form.stock.id_for_label }}" class="form-control bg-primary ">Stock disponible: </label>
                            <div class="form-control-color">{{ form.stock }}</div>
                        </div>
                        <div>
                            <label for="{{ form.personalizable.id_for_label }}" class="text-light ">Es personalizable: </label>
                            <div class="form-control-color">{{ form.personalizable }}</div>
                        </div>
                        <div>
                            <label for="{{ form.imagen.id_for_label }}" class="text-light ">Imagen del producto: </label>
                            <div class="form-control-color">{{ form.imagen }}</div>
                        </div>


                       
                        <button type="submit">Guardar</button>
                    </form> 
                </div>
            </div>
        </div>
    {% endblock CONTENIDO_INDEX %}

project/apps/producto/templates/producto/producto_list.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <h1>Productos Disponibles</h1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    {% if object_list %}
    <div>
        <form action="{% url 'producto:producto_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar...">
        </form>
    </div>

    {% for object in object_list %}
        <div class="container bg-transparent   text-start  ">
            <ul>
                {{ object.nombre }} ${{ object.precio}}
                <div class="column-gap-2 ">
                    <a href="{% url 'producto:producto_detail' object.id %}" class="btn btn-secondary  btn-sn">Ver detalle</a>
                    {% if user.is_staff %}
                        <a href="{% url 'producto:producto_update' object.id %}" class="btn btn-secondary  btn-sn">Actualizar</a> 
                        <a href="{% url 'producto:producto_delete' object.id %}" class="btn btn-secondary  btn-sn">Eliminar</a> 
                    {% endif %}
                    
                </div>

            </ul>
        <br>
        </div>
    {% endfor %}        
    {% else %}
    <p>no hay productos</p>
    {% endif %}
    {% if user.is_staff %}
        <a href="{% url 'producto:producto_create' %}">Agregar producto</a>
    {% endif %}
    
{% endblock CONTENIDO_INDEX %}