project/apps/cliente/urls.py
from django.urls import path
from .views import home, register, login_request, registrar_cliente, CiudadCreate
from django.contrib.auth.views import LogoutView
app_name = "cliente"

urlpatterns = [
    path("", home, name="home"),
    path('register/', register, name="register"),
    path('crear/cliente/', registrar_cliente, name="crear_cliente"),
    path('login/', login_request , name="login"),
    path('logout/', LogoutView.as_view(template_name="cliente/logout.html"), name="logout"),
    path('registrar/ciudad', CiudadCreate.as_view(), name="registrar_ciudad"),
]

project/apps/venta/urls.py
from django.urls import path
from . import views

app_name = "venta"

urlpatterns = [
    path("", views.home, name="home"),
    path("registrar/pedido/", views.registrar_pedido, name="registrar_pedido"),
    path("venta/list/", views.VentaList.as_view(), name="venta_list"),
    path("registrar/tiposervicio/", views.TipoServicioCreateView.as_view(), name="registrar_tiposervicio"),
    path("servicios", views.servicios, name="servicios"),
    path("registrar/servicio/", views.ServicioCreateView.as_view(), name="registrar_servicio"),
    path("confirmar", views.confirmar, name="confirmar"),
    path('servicio/list/', views.ServicioList.as_view(), name="servicio_list"),
    path("servicio/detail/<int:pk>", views.ServicioDetail.as_view(), name="servicio_detail"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/venta/models.py
from django.db import models
from producto.models import Producto
from cliente.models import Cliente

# Create your models here.

class Venta (models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    producto_id = models.ForeignKey(Producto, on_delete=models.SET_NULL, blank=True, null=True)
    cliente_id = models.ForeignKey(Cliente, on_delete=models.SET_NULL, blank=True, null=True)
    cantidad = models.PositiveIntegerField(default=1, null=False, blank=False)
    
    def subtotal(self):
        subtotal = self.producto_id.precio * self.cantidad
        return subtotal

    def __str__(self):
        return f"{self.cliente_id} compró {self.cantidad} {self.producto_id}. Total ${self.subtotal()}"
    

class TipoServicio(models.Model):
    nombre = models.CharField(max_length=150, blank=False, null=False)
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    fecha = models.DateField(auto_now_add=True)
    tiposervicio_id = models.ForeignKey(TipoServicio, on_delete=models.SET_NULL, null=True, blank=True)
    cliente_id = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True)
    fecha_servicio = models.DateField(blank=False, null=False)
    detalle = models.CharField(max_length=400, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    imagen = models.ImageField(upload_to='img_servicios', blank=True, null=True)

    def __str__(self):
        return f"Fecha de Solicitud {self.fecha.strftime('%Y-%m-%d')}, servicio {self.tiposervicio_id.nombre}, para el {self.fecha_servicio.strftime('%Y-%m-%d')}"

project/apps/venta/forms.py
from django import forms
from .models import Venta, Servicio, TipoServicio

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ["producto_id", "cliente_id", "cantidad"]

class TipoServicioForm(forms.ModelForm):
    class Meta:
        model = TipoServicio
        fields = "__all__"

class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servicio
        fields = "__all__"
        widget = forms.DateInput(attrs={'type': 'date'})

project/apps/venta/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .forms import VentaForm, TipoServicioForm, ServicioForm
from .models import Venta, Servicio, TipoServicio
from django.http import HttpRequest, HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import ListView, CreateView, DetailView
from django.urls import reverse_lazy

def home (request):
    return render (request, 'venta/index.html')

def registrar_pedido(request: HttpRequest) -> HttpResponse:
    # Desde esta función los usuarios pueden registrar sus pedidos
    if request.method == "POST":
        form = VentaForm(request.POST)
        if form.is_valid():
            form.save()            
            return render(request, "home/index.html", {"mensaje": "Pedido registrado, nos comunicaremos a la brevedad. Muchas Gracias!"})
    else:  
        form = VentaForm()
        
    return render(request, "venta/registrar_pedido.html", {"form": form})


class VentaList(ListView):
    # Desde esta función un usuario miembro del staff puede listar todos los pedidos recibidos
    model = Venta

class TipoServicioCreateView(CreateView):
     # Desde esta función un usuario miembro del staff puede crear tipos de servicio
    model = TipoServicio
    form_class = TipoServicioForm
    success_url = reverse_lazy("venta:servicios")

def servicios(request):
    # Desde esta función se podrá visualizar todos los servicios disponibles
    servicios_registro = TipoServicio.objects.all()
    contexto = {"servicios": servicios_registro}
    return render (request, 'venta/servicios.html', contexto)

class ServicioCreateView(CreateView):
    # Desde esta función un usuario puede solicitar un servicio
    model = Servicio
    form_class = ServicioForm
    success_url = reverse_lazy("venta:confirmar")

def confirmar (request):
    # Esta función avisa al usuario que se registró su pedido
    return render(request, "venta/confirmar.html")

class ServicioList(ListView):
    # Desde esta función un usuario miembro del staff puede listar los servicios solicitados
    model = Servicio
    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = Servicio.objects.filter(fecha_servicio__icontains=consulta)
        else:
            object_list = Servicio.objects.all()
        return object_list
    
class ServicioDetail(DetailView):
    # Desde esta función un usuario miembro del staff puede ver el detalle de un servicio solicitado
    model = Servicio

project/apps/venta/templates/venta/confirmar.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <H1>Gracias por registrar su solicitud de servicio</H1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <h3>Nos pondremos en contacto con usted a la brevedad</h3>
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/index.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <H1>Realizar Pedido</H1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <h3>Tenga en cuenta que para realizar un pedido debe registrar sus datos de cliente</h3>
    <li><a href="{% url 'cliente:crear_cliente' %}">Registrar datos de cliente</a></li>
    <li><a href="{% url 'venta:registrar_pedido' %}">Registrar nuevo pedido</a></li>
    {% if user.is_staff %}
        <li><a href="{% url 'venta:venta_list' %}">Ver las ventas realizadas</a></li>
    {% endif %}
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/registrar_pedido.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <h1>Registrar Pedido</h1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    
        <div class="row align-items-stretch mb-5">
            <div class="col-md-6">
                <div class="form-group">
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <label for="{{ form.producto_id.id_for_label }}" class="form-control bg-primary">Producto: </label>
                            <div class="form-control-color">{{ form.producto_id }}</div>
                        </div>
                        <div>
                            <label for="{{ form.cliente_id.id_for_label }}" class="form-control bg-primary ">Cliente: </label>
                            <div class="form-control-color">{{ form.cliente_id }} </div>
                        </div>
                        <div>
                            <label for="{{ form.cantidad.id_for_label }}" class="form-control bg-primary ">Cantidad: </label>
                            <div class="text-start ">{{ form.cantidad }}</div>
                        </div>         

                        <button type="submit">Guardar</button>
                    </form> 
                </div>
            </div>
        </div>
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/servicio_detail.html
{% extends 'home/index.html' %}
{% load static %}

{% block TITULO_INDEX %}
    <h6>{{ object }}</h6>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <div class="container bg-gradient text-black fw-bold ">
        <ul>Tipo de servicio: {{ object.tiposervicio_id }} </ul>
        <ul>Cliente: {{ object.cliente_id }}</ul>
        <ul>Contacto: {{ object.cliente_id.contacto }}</ul>
        <ul>Domicilio: {{ object.cliente_id.domicilio }}</ul>
        <ul>Ciudad: {{ object.cliente_id.ciudad_id }}</ul>
        <ul>Fecha de servicio solicitada: {{ object.fecha_servicio }} </ul>  
        <ul>Detalle: {{ object.detalle }}</ul>
        <ul>Color: {{ object.color }}</ul>
        {% if object.imagen.url %}
            <ul><img src="{{ object.imagen.url }}" alt="imagen" width="200" ></ul>
        {% endif %}
        
    </div>
<!-- tiposervicio_id, cliente_id, fecha_servicio, detalle, color, imagen -->
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/servicio_form.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    Solicitar Servicio
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <div class="row align-items-stretch mb-5">
        <div class="col-md-6">
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.tiposervicio_id.id_for_label }}" class="form-control bg-primary">Tipo de Servicio: </label>
                        <div class="form-control-color">{{ form.tiposervicio_id }}</div>
                    </div>    
                    <div>
                        <label for="{{ form.cliente_id.id_for_label }}" class="form-control bg-primary">Cliente: </label>
                        <div class="form-control-color">{{ form.cliente_id }}</div>
                    </div>
                    <div>
                        <label for="{{ form.fecha_servicio.id_for_label }}" class="form-control bg-primary">Fecha de servicio: </label>
                        <span class="tooltip-text">Tenga en cuenta ingresar una fecha posterior a hoy. Nos contactaremos con usted para coordinar la visita</span>
                        <div class="form-control-color">{{ form.fecha_servicio }}</div>
                    </div>
                    <div>
                        <label for="{{ form.detalle.id_for_label }}" class="form-control bg-primary">Detalle/Aclaración: </label>
                        <div class="form-control-color ">{{ form.detalle }}</div>
                    </div>
                    <div>
                        <label for="{{ form.color.id_for_label }}" class="form-control bg-primary" >Color: </label>
                        <span class="tooltip-text">Colores disponibles: Negro, Gris, Blanco, Rojo, Azul, Verde, Rosa, Celeste, Violeta, Lila y Dorado.</span>
                        <div class="form-control-color">{{ form.color }}</div>
                    </div>
                    <div>
                        <label for="{{ form.imagen.id_for_label }}" class="form-control bg-primary">Imagen: </label>
                        <span class="tooltip-text">Recuerde que los diseños deben ser vectores de colores planos (No realizamos impresiones)</span>
                        <div class="form-control-color">{{ form.imagen }}</div>
                    </div>
                    <button type="submit">Guardar</button>
                </form> 
            </div>
        </div>
    </div>
    <!-- tiposervicio_id, cliente_id, fecha_servicio, detalle, color, imagen -->
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/servicio_list.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <h1>Servicios Solicitados</h1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    {% if object_list %}
    <div>
        <span class="tooltip-text">Buscar por fecha solicita para el servicio</span>
        <form action="{% url 'venta:servicio_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar...">
        </form>
    </div>

    {% for object in object_list %}
        <div class="container bg-transparent   text-start  ">
            <ul>
                {{ object.fecha }} {{ object.tiposervicio_id }}
                <div class="column-gap-2 ">
                    <a href="{% url 'venta:servicio_detail' object.id %}" class="btn btn-secondary  btn-sn">Ver detalle</a>  
                </div>

            </ul>
        <br>
        </div>
    {% endfor %}        
    {% else %}
    <p>No se solicitaron servicios</p>
    {% endif %}
    
{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/servicios.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    <h1>Servicios</h1>
{% endblock TITULO_INDEX %}

{% block CONTENIDO_INDEX %}
    <h3>Realizamos servicio de producción y colocación de vinilos</h3>
    <h4>Acá vas a encontrar los tipos de servicios y sus precios, además vas a poder realizar tu pedido y reserva de turno</h4>
    {% for servicio in servicios %}
            <div class="container">
                <h5 class="text-primary">{{ servicio.nombre }} ${{ servicio.precio }}</h5>  
            </div>
    {% endfor %}
    <a href="{% url 'venta:registrar_servicio' %}", class="btn btn-secondary  btn-sn">Solicitar servicio</a>
    {% if user.is_staff %}
        <div>
            <ul><a href="{% url 'venta:registrar_tiposervicio' %}">Registrar nuevo tipo de servicio</a></ul>
            <ul><a href="{% url 'venta:servicio_list' %}">Ver servicios solicitados</a></ul>
        </div>
    {% endif %}
    

{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/tiposervicio_form.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    Registrar Tipo de Servicio
{% endblock TITULO_INDEX %}


{% block CONTENIDO_INDEX %}
    <div class="row align-items-stretch mb-5">
        <div class="col-md-6">
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.nombre.id_for_label }}" class="form-control bg-primary">Tipo de Servicio: </label>
                        <div class="form-control-color">{{ form.nombre }}</div>
                    </div>    
                    <div>
                        <label for="{{ form.precio.id_for_label }}" class="form-control bg-primary">Precio de Servicio: </label>
                        <div class="form-control-color">{{ form.precio }}</div>
                    </div>
                    
                    <button type="submit">Guardar</button>
                </form> 
            </div>
        </div>
    </div>

{% endblock CONTENIDO_INDEX %}

project/apps/venta/templates/venta/venta_list.html
{% extends 'home/index.html' %}
{% load static %}
    {% block TITULO_INDEX %}
        <h1>Ventas</h1>
    {% endblock TITULO_INDEX %}
    
    {% block CONTENIDO_INDEX %}
        {% if object_list %}
       
    
        {% for object in object_list %}
            <div class="container bg-transparent   text-start  ">
                    <h2 class="text-primary text-start  ">{{ object.fecha }}</h2>
                    <div class="text-start ">
                        <ul>Cliente: {{ object.cliente_id }} - Contacto: {{ object.cliente_id.contacto }}</ul>
                        <ul>Producto: {{ object.producto_id }}</ul> 
                        <ul><img src="{{ object.producto_id.imagen.url }}" alt="{{ object.producto_id }}" width="200"></ul>
                        <ul>Cantidad: {{ object.cantidad }}</ul>
                        <ul>Total: {{ object.subtotal }}</ul>
                    </div>
            <br>
            </div>
        {% endfor %}        
        {% else %}
        <p>No hay ventas registradas</p>
        {% endif %}
        
        
    {% endblock CONTENIDO_INDEX %}