project/apps/cliente/urls.py
from django.urls import path
from .views import home, register, login_request, registrar_cliente, CiudadCreate
from django.contrib.auth.views import LogoutView
app_name = "cliente"

urlpatterns = [
    path("", home, name="home"),
    path('register/', register, name="register"),
    path('crear/cliente/', registrar_cliente, name="crear_cliente"),
    path('login/', login_request , name="login"),
    path('logout/', LogoutView.as_view(template_name="cliente/logout.html"), name="logout"),
    path('registrar/ciudad', CiudadCreate.as_view(), name="registrar_ciudad"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls')),
    path('', include('home.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/cliente/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Ciudad(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return self.nombre

class Cliente (models.Model):
    nombre = models.CharField(max_length=20, blank=False, null=False)
    apellido = models.CharField(max_length=20, blank=False, null=False)
    documento = models.IntegerField(max_length=8, blank=True, null=True)
    contacto = models.IntegerField(max_length=15, blank=True, null=True)
    domicilio = models.CharField(max_length=50, blank=True, null=True)
    nacimiento = models.DateField(null=True)
    ciudad_id = models.ForeignKey(Ciudad, blank=True, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

project/apps/cliente/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Cliente, Ciudad


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = "__all__"

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = "__all__"


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control, text-align"}),
            "email": forms.EmailInput(attrs={"class": "form-control, text-align"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/apps/cliente/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect, render
from .models import Cliente, Ciudad
from .forms import ClienteForm, CiudadForm
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from . import forms
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import UpdateView, CreateView
# Create your views here.

@staff_member_required
def home(request):
    # Desde esta función un usuario parte del staff podrá visualizar todos los clientes registrados
    clientes_registros = Cliente.objects.all()
    contexto = {"clientes": clientes_registros}
    return render(request, "cliente/index.html", contexto)

def registrar_cliente(request: HttpRequest) -> HttpResponse:
    # Desde esta función los usuarios podrán registrar sus datos de cliente para posteriormente realizar pedidos
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "home/index.html", {"mensaje": "Registró sus datos correctamente"})
    else:  
        form = ClienteForm()
    return render(request, "cliente/crear.html", {"form": form})

class CiudadCreate(CreateView):
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy("cliente:crear_cliente")


def register(request: HttpRequest) -> HttpResponse:
    # Registro de usuarios
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "home/index.html", {"mensaje": "Usuario creado 😊"})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "cliente/register.html", {"form": form})


def login_request(request: HttpRequest) -> HttpResponse:
    # Inicio de sesión
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "home/index.html", {"mensaje": "Inició sesión correctamente"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "cliente/login.html", {"form": form})

project/apps/cliente/templates/cliente/ciudad_form.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    Registrar Ciudad
{% endblock TITULO_INDEX %}


{% block CONTENIDO_INDEX %}
    <div class="row align-items-stretch mb-5">
        <div class="col-md-6">
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.nombre.id_for_label }}" class="form-control bg-primary">Ciudad: </label>
                        <div class="form-control-color">{{ form.nombre }}</div>
                    </div>                
                    <button type="submit">Guardar</button>
                </form> 
            </div>
        </div>
    </div>

{% endblock CONTENIDO_INDEX %}

project/apps/cliente/templates/cliente/crear.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    Registrar Cliente
{% endblock TITULO_INDEX %}


{% block CONTENIDO_INDEX %}
    <p class="card-subtitle ">Para realizar pedidos necesitamos que registre sus datos</p>

    <div class="row align-items-stretch mb-5">
        <div class="col-md-6">
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.nombre.id_for_label }}" class="form-control bg-primary">Nombre: </label>
                        <div class="form-control-color">{{ form.nombre }}</div>
                    </div>
                    <div>
                        <label for="{{ form.apellido.id_for_label }}" class="form-control bg-primary ">Apellido: </label>
                        <div class="form-control-color">{{ form.apellido }} </div> 
                    </div>
                    <div>
                        <label for="{{ form.documento.id_for_label }}" class="form-control bg-primary ">Documento: </label>
                        <div class="text-start ">{{ form.documento }}</div>
                    </div>
                    <div>
                        <label for="{{ form.contacto.id_for_label }}" class="form-control bg-primary ">Contacto: </label>
                        <div class="form-control-color">{{ form.contacto }}</div>
                    </div>
                    <div>
                        <label for="{{ form.domicilio.id_for_label }}" class="form-control bg-primary ">Domicilio: </label>
                        <div class="form-control-color">{{ form.domicilio }}</div>
                    </div>
                    <div>
                        <label for="{{ form.nacimiento.id_for_label }}" class="text-light ">Fecha de Nacimiento: </label>
                        <div class="form-control-color">{{ form.nacimiento }}</div>
                    </div>
                    <div>
                        <label for="{{ form.ciudad_id.id_for_label }}" class="text-light ">Ciudad de origen: </label>
                        <div class="form-control-color">{{ form.ciudad_id }}</div> <div><a href="{% url 'cliente:registrar_ciudad' %}">Agregar Ciudad</a></div>
                    </div>


                   
                    <button type="submit">Guardar</button>
                </form> 
            </div>
        </div>
    </div>

{% endblock CONTENIDO_INDEX %}

project/apps/cliente/templates/cliente/index.html
{% extends 'home/index.html' %}

    {% block TITULO_INDEX %}
        <h1>Clientes</h1>
    {% endblock TITULO_INDEX %}

    {% block CONTENIDO_INDEX %}

        {% for cliente in clientes %}
            <div class="container">
                <h2 class="text-primary text-start  ">{{ cliente.apellido }}, {{ cliente.nombre }}</h2>
                <div class="text-start ">
                    {% if cliente.documento != None %}
                        <ul>Documento: {{ cliente.documento }}</ul>
                    {% endif %}
                    
                    <ul>Contacto: {{ cliente.contacto }}</ul>
                    <ul>Domicilio: {{ cliente.domicilio }}</ul>
                    <ul>Fecha de nacimiento: {{ cliente.nacimiento }}</ul>
                    <ul>Ciudad de Orígen: {{ cliente.ciudad_id }}</ul>
                </div>
            </div>
        {% endfor %}
        <!-- "nombre", "apellido", "documento", "contacto", "domicilio", "nacimiento", "ciudad_id" -->
    {% endblock CONTENIDO_INDEX %}

project/apps/cliente/templates/cliente/login.html
{% extends 'home/index.html' %}

{% block TITULO_INDEX %}
    Login
{% endblock TITULO_INDEX %}


{% block CONTENIDO_INDEX %}

    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <div class=""> 
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </div>
    </form>

{% endblock CONTENIDO_INDEX %}

project/apps/cliente/templates/cliente/logout.html
{% extends 'home/index.html' %}

{% block CONTENIDO_INDEX %}
    <div class="fs-3 fst-italic ">
        <p>Has cerrado sesión</p>
    </div>
{% endblock %}

project/apps/cliente/templates/cliente/register.html
{% extends 'Home/index.html' %}

{% block TITULO_INDEX %}
    Crear Usuario
{% endblock TITULO_INDEX %}


{% block CONTENIDO_INDEX %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>

{% endblock CONTENIDO_INDEX %}